package scripting

// Code generated by peg -inline friendscript.peg DO NOT EDIT.

import (
	"fmt"
	"io"
	"os"
	"sort"
	"strconv"
	"strings"
)

const endSymbol rune = 1114112

/* The rule types inferred from the grammar are below. */
type pegRule uint8

const (
	ruleUnknown pegRule = iota
	ruleFriendscript
	rule_
	rule__
	ruleASSIGN
	ruleTRIQUOT
	ruleBREAK
	ruleCLOSE
	ruleCOLON
	ruleCOMMA
	ruleCOMMENT
	ruleCONT
	ruleCOUNT
	ruleDECLARE
	ruleDOT
	ruleELSE
	ruleIF
	ruleIN
	ruleINCLUDE
	ruleLOOP
	ruleNOOP
	ruleNOT
	ruleOPEN
	ruleSQOPEN
	ruleSQCLOSE
	ruleSCOPE
	ruleSEMI
	ruleSHEBANG
	ruleSKIPVAR
	ruleUNSET
	ruleScalarType
	ruleIdentifier
	ruleFloat
	ruleBoolean
	ruleInteger
	rulePositiveInteger
	ruleString
	ruleStringLiteral
	ruleStringInterpolated
	ruleTriquote
	ruleTriquoteBody
	ruleNullValue
	ruleObject
	ruleArray
	ruleRegularExpression
	ruleKeyValuePair
	ruleKey
	ruleKValue
	ruleType
	ruleExponentiate
	ruleMultiply
	ruleDivide
	ruleModulus
	ruleAdd
	ruleSubtract
	ruleBitwiseAnd
	ruleBitwiseOr
	ruleBitwiseNot
	ruleBitwiseXor
	ruleMatchOperator
	ruleUnmatch
	ruleMatch
	ruleOperator
	ruleAssignmentOperator
	ruleAssignEq
	ruleStarEq
	ruleDivEq
	rulePlusEq
	ruleMinusEq
	ruleAndEq
	ruleOrEq
	ruleAppend
	ruleComparisonOperator
	ruleEquality
	ruleNonEquality
	ruleGreaterThan
	ruleGreaterEqual
	ruleLessEqual
	ruleLessThan
	ruleMembership
	ruleNonMembership
	ruleVariable
	ruleVariableNameSequence
	ruleVariableName
	ruleVariableIndex
	ruleBlock
	ruleFlowControlWord
	ruleFlowControlBreak
	ruleFlowControlContinue
	ruleStatementBlock
	ruleAssignment
	ruleAssignmentLHS
	ruleAssignmentRHS
	ruleVariableSequence
	ruleExpressionSequence
	ruleExpression
	ruleExpressionLHS
	ruleExpressionRHS
	ruleInlineCommand
	ruleValueYielding
	ruleDirective
	ruleDirectiveUnset
	ruleDirectiveInclude
	ruleDirectiveDeclare
	ruleCommand
	ruleCommandName
	ruleCommandFirstArg
	ruleCommandSecondArg
	ruleCommandResultAssignment
	ruleConditional
	ruleIfStanza
	ruleElseIfStanza
	ruleElseStanza
	ruleLoop
	ruleLoopConditionFixedLength
	ruleLoopConditionIterable
	ruleLoopIterableLHS
	ruleLoopIterableRHS
	ruleLoopConditionBounded
	ruleLoopConditionTruthy
	ruleConditionalExpression
	ruleConditionWithAssignment
	ruleConditionWithCommand
	ruleConditionWithRegex
	ruleConditionWithComparator
	ruleConditionWithComparatorLHS
	ruleConditionWithComparatorRHS
)

var rul3s = [...]string{
	"Unknown",
	"Friendscript",
	"_",
	"__",
	"ASSIGN",
	"TRIQUOT",
	"BREAK",
	"CLOSE",
	"COLON",
	"COMMA",
	"COMMENT",
	"CONT",
	"COUNT",
	"DECLARE",
	"DOT",
	"ELSE",
	"IF",
	"IN",
	"INCLUDE",
	"LOOP",
	"NOOP",
	"NOT",
	"OPEN",
	"SQOPEN",
	"SQCLOSE",
	"SCOPE",
	"SEMI",
	"SHEBANG",
	"SKIPVAR",
	"UNSET",
	"ScalarType",
	"Identifier",
	"Float",
	"Boolean",
	"Integer",
	"PositiveInteger",
	"String",
	"StringLiteral",
	"StringInterpolated",
	"Triquote",
	"TriquoteBody",
	"NullValue",
	"Object",
	"Array",
	"RegularExpression",
	"KeyValuePair",
	"Key",
	"KValue",
	"Type",
	"Exponentiate",
	"Multiply",
	"Divide",
	"Modulus",
	"Add",
	"Subtract",
	"BitwiseAnd",
	"BitwiseOr",
	"BitwiseNot",
	"BitwiseXor",
	"MatchOperator",
	"Unmatch",
	"Match",
	"Operator",
	"AssignmentOperator",
	"AssignEq",
	"StarEq",
	"DivEq",
	"PlusEq",
	"MinusEq",
	"AndEq",
	"OrEq",
	"Append",
	"ComparisonOperator",
	"Equality",
	"NonEquality",
	"GreaterThan",
	"GreaterEqual",
	"LessEqual",
	"LessThan",
	"Membership",
	"NonMembership",
	"Variable",
	"VariableNameSequence",
	"VariableName",
	"VariableIndex",
	"Block",
	"FlowControlWord",
	"FlowControlBreak",
	"FlowControlContinue",
	"StatementBlock",
	"Assignment",
	"AssignmentLHS",
	"AssignmentRHS",
	"VariableSequence",
	"ExpressionSequence",
	"Expression",
	"ExpressionLHS",
	"ExpressionRHS",
	"InlineCommand",
	"ValueYielding",
	"Directive",
	"DirectiveUnset",
	"DirectiveInclude",
	"DirectiveDeclare",
	"Command",
	"CommandName",
	"CommandFirstArg",
	"CommandSecondArg",
	"CommandResultAssignment",
	"Conditional",
	"IfStanza",
	"ElseIfStanza",
	"ElseStanza",
	"Loop",
	"LoopConditionFixedLength",
	"LoopConditionIterable",
	"LoopIterableLHS",
	"LoopIterableRHS",
	"LoopConditionBounded",
	"LoopConditionTruthy",
	"ConditionalExpression",
	"ConditionWithAssignment",
	"ConditionWithCommand",
	"ConditionWithRegex",
	"ConditionWithComparator",
	"ConditionWithComparatorLHS",
	"ConditionWithComparatorRHS",
}

type token32 struct {
	pegRule
	begin, end uint32
}

func (t *token32) String() string {
	return fmt.Sprintf("\x1B[34m%v\x1B[m %v %v", rul3s[t.pegRule], t.begin, t.end)
}

type node32 struct {
	token32
	up, next *node32
}

func (node *node32) print(w io.Writer, pretty bool, buffer string) {
	var print func(node *node32, depth int)
	print = func(node *node32, depth int) {
		for node != nil {
			for c := 0; c < depth; c++ {
				fmt.Fprintf(w, " ")
			}
			rule := rul3s[node.pegRule]
			quote := strconv.Quote(string(([]rune(buffer)[node.begin:node.end])))
			if !pretty {
				fmt.Fprintf(w, "%v %v\n", rule, quote)
			} else {
				fmt.Fprintf(w, "\x1B[36m%v\x1B[m %v\n", rule, quote)
			}
			if node.up != nil {
				print(node.up, depth+1)
			}
			node = node.next
		}
	}
	print(node, 0)
}

func (node *node32) Print(w io.Writer, buffer string) {
	node.print(w, false, buffer)
}

func (node *node32) PrettyPrint(w io.Writer, buffer string) {
	node.print(w, true, buffer)
}

type tokens32 struct {
	tree []token32
}

func (t *tokens32) Trim(length uint32) {
	t.tree = t.tree[:length]
}

func (t *tokens32) Print() {
	for _, token := range t.tree {
		fmt.Println(token.String())
	}
}

func (t *tokens32) AST() *node32 {
	type element struct {
		node *node32
		down *element
	}
	tokens := t.Tokens()
	var stack *element
	for _, token := range tokens {
		if token.begin == token.end {
			continue
		}
		node := &node32{token32: token}
		for stack != nil && stack.node.begin >= token.begin && stack.node.end <= token.end {
			stack.node.next = node.up
			node.up = stack.node
			stack = stack.down
		}
		stack = &element{node: node, down: stack}
	}
	if stack != nil {
		return stack.node
	}
	return nil
}

func (t *tokens32) PrintSyntaxTree(buffer string) {
	t.AST().Print(os.Stdout, buffer)
}

func (t *tokens32) WriteSyntaxTree(w io.Writer, buffer string) {
	t.AST().Print(w, buffer)
}

func (t *tokens32) PrettyPrintSyntaxTree(buffer string) {
	t.AST().PrettyPrint(os.Stdout, buffer)
}

func (t *tokens32) Add(rule pegRule, begin, end, index uint32) {
	tree, i := t.tree, int(index)
	if i >= len(tree) {
		t.tree = append(tree, token32{pegRule: rule, begin: begin, end: end})
		return
	}
	tree[i] = token32{pegRule: rule, begin: begin, end: end}
}

func (t *tokens32) Tokens() []token32 {
	return t.tree
}

type Friendscript struct {
	runtime

	Buffer string
	buffer []rune
	rules  [127]func() bool
	parse  func(rule ...int) error
	reset  func()
	Pretty bool
	tokens32
}

func (p *Friendscript) Parse(rule ...int) error {
	return p.parse(rule...)
}

func (p *Friendscript) Reset() {
	p.reset()
}

type textPosition struct {
	line, symbol int
}

type textPositionMap map[int]textPosition

func translatePositions(buffer []rune, positions []int) textPositionMap {
	length, translations, j, line, symbol := len(positions), make(textPositionMap, len(positions)), 0, 1, 0
	sort.Ints(positions)

search:
	for i, c := range buffer {
		if c == '\n' {
			line, symbol = line+1, 0
		} else {
			symbol++
		}
		if i == positions[j] {
			translations[positions[j]] = textPosition{line, symbol}
			for j++; j < length; j++ {
				if i != positions[j] {
					continue search
				}
			}
			break search
		}
	}

	return translations
}

type parseError struct {
	p   *Friendscript
	max token32
}

func (e *parseError) Error() string {
	tokens, err := []token32{e.max}, "\n"
	positions, p := make([]int, 2*len(tokens)), 0
	for _, token := range tokens {
		positions[p], p = int(token.begin), p+1
		positions[p], p = int(token.end), p+1
	}
	translations := translatePositions(e.p.buffer, positions)
	format := "parse error near %v (line %v symbol %v - line %v symbol %v):\n%v\n"
	if e.p.Pretty {
		format = "parse error near \x1B[34m%v\x1B[m (line %v symbol %v - line %v symbol %v):\n%v\n"
	}
	for _, token := range tokens {
		begin, end := int(token.begin), int(token.end)
		err += fmt.Sprintf(format,
			rul3s[token.pegRule],
			translations[begin].line, translations[begin].symbol,
			translations[end].line, translations[end].symbol,
			strconv.Quote(string(e.p.buffer[begin:end])))
	}

	return err
}

func (p *Friendscript) PrintSyntaxTree() {
	if p.Pretty {
		p.tokens32.PrettyPrintSyntaxTree(p.Buffer)
	} else {
		p.tokens32.PrintSyntaxTree(p.Buffer)
	}
}

func (p *Friendscript) WriteSyntaxTree(w io.Writer) {
	p.tokens32.WriteSyntaxTree(w, p.Buffer)
}

func (p *Friendscript) SprintSyntaxTree() string {
	var bldr strings.Builder
	p.WriteSyntaxTree(&bldr)
	return bldr.String()
}

func Pretty(pretty bool) func(*Friendscript) error {
	return func(p *Friendscript) error {
		p.Pretty = pretty
		return nil
	}
}

func Size(size int) func(*Friendscript) error {
	return func(p *Friendscript) error {
		p.tokens32 = tokens32{tree: make([]token32, 0, size)}
		return nil
	}
}
func (p *Friendscript) Init(options ...func(*Friendscript) error) error {
	var (
		max                  token32
		position, tokenIndex uint32
		buffer               []rune
	)
	for _, option := range options {
		err := option(p)
		if err != nil {
			return err
		}
	}
	p.reset = func() {
		max = token32{}
		position, tokenIndex = 0, 0

		p.buffer = []rune(p.Buffer)
		if len(p.buffer) == 0 || p.buffer[len(p.buffer)-1] != endSymbol {
			p.buffer = append(p.buffer, endSymbol)
		}
		buffer = p.buffer
	}
	p.reset()

	_rules := p.rules
	tree := p.tokens32
	p.parse = func(rule ...int) error {
		r := 1
		if len(rule) > 0 {
			r = rule[0]
		}
		matches := p.rules[r]()
		p.tokens32 = tree
		if matches {
			p.Trim(tokenIndex)
			return nil
		}
		return &parseError{p, max}
	}

	add := func(rule pegRule, begin uint32) {
		tree.Add(rule, begin, position, tokenIndex)
		tokenIndex++
		if begin != position && position > max.end {
			max = token32{rule, begin, position}
		}
	}

	matchDot := func() bool {
		if buffer[position] != endSymbol {
			position++
			return true
		}
		return false
	}

	/*matchChar := func(c byte) bool {
		if buffer[position] == c {
			position++
			return true
		}
		return false
	}*/

	/*matchRange := func(lower byte, upper byte) bool {
		if c := buffer[position]; c >= lower && c <= upper {
			position++
			return true
		}
		return false
	}*/

	_rules = [...]func() bool{
		nil,
		/* 0 Friendscript <- <(_ SHEBANG? _ Block* !.)> */
		func() bool {
			position0, tokenIndex0 := position, tokenIndex
			{
				position1 := position
				if !_rules[rule_]() {
					goto l0
				}
				{
					position2, tokenIndex2 := position, tokenIndex
					{
						position4 := position
						if buffer[position] != rune('#') {
							goto l2
						}
						position++
						if buffer[position] != rune('!') {
							goto l2
						}
						position++
						{
							position7, tokenIndex7 := position, tokenIndex
							if buffer[position] != rune('\n') {
								goto l7
							}
							position++
							goto l2
						l7:
							position, tokenIndex = position7, tokenIndex7
						}
						if !matchDot() {
							goto l2
						}
					l5:
						{
							position6, tokenIndex6 := position, tokenIndex
							{
								position8, tokenIndex8 := position, tokenIndex
								if buffer[position] != rune('\n') {
									goto l8
								}
								position++
								goto l6
							l8:
								position, tokenIndex = position8, tokenIndex8
							}
							if !matchDot() {
								goto l6
							}
							goto l5
						l6:
							position, tokenIndex = position6, tokenIndex6
						}
						if buffer[position] != rune('\n') {
							goto l2
						}
						position++
						add(ruleSHEBANG, position4)
					}
					goto l3
				l2:
					position, tokenIndex = position2, tokenIndex2
				}
			l3:
				if !_rules[rule_]() {
					goto l0
				}
			l9:
				{
					position10, tokenIndex10 := position, tokenIndex
					if !_rules[ruleBlock]() {
						goto l10
					}
					goto l9
				l10:
					position, tokenIndex = position10, tokenIndex10
				}
				{
					position11, tokenIndex11 := position, tokenIndex
					if !matchDot() {
						goto l11
					}
					goto l0
				l11:
					position, tokenIndex = position11, tokenIndex11
				}
				add(ruleFriendscript, position1)
			}
			return true
		l0:
			position, tokenIndex = position0, tokenIndex0
			return false
		},
		/* 1 _ <- <(' ' / '\t' / '\r' / '\n')*> */
		func() bool {
			{
				position13 := position
			l14:
				{
					position15, tokenIndex15 := position, tokenIndex
					{
						position16, tokenIndex16 := position, tokenIndex
						if buffer[position] != rune(' ') {
							goto l17
						}
						position++
						goto l16
					l17:
						position, tokenIndex = position16, tokenIndex16
						if buffer[position] != rune('\t') {
							goto l18
						}
						position++
						goto l16
					l18:
						position, tokenIndex = position16, tokenIndex16
						if buffer[position] != rune('\r') {
							goto l19
						}
						position++
						goto l16
					l19:
						position, tokenIndex = position16, tokenIndex16
						if buffer[position] != rune('\n') {
							goto l15
						}
						position++
					}
				l16:
					goto l14
				l15:
					position, tokenIndex = position15, tokenIndex15
				}
				add(rule_, position13)
			}
			return true
		},
		/* 2 __ <- <(' ' / '\t' / '\r' / '\n')+> */
		func() bool {
			position20, tokenIndex20 := position, tokenIndex
			{
				position21 := position
				{
					position24, tokenIndex24 := position, tokenIndex
					if buffer[position] != rune(' ') {
						goto l25
					}
					position++
					goto l24
				l25:
					position, tokenIndex = position24, tokenIndex24
					if buffer[position] != rune('\t') {
						goto l26
					}
					position++
					goto l24
				l26:
					position, tokenIndex = position24, tokenIndex24
					if buffer[position] != rune('\r') {
						goto l27
					}
					position++
					goto l24
				l27:
					position, tokenIndex = position24, tokenIndex24
					if buffer[position] != rune('\n') {
						goto l20
					}
					position++
				}
			l24:
			l22:
				{
					position23, tokenIndex23 := position, tokenIndex
					{
						position28, tokenIndex28 := position, tokenIndex
						if buffer[position] != rune(' ') {
							goto l29
						}
						position++
						goto l28
					l29:
						position, tokenIndex = position28, tokenIndex28
						if buffer[position] != rune('\t') {
							goto l30
						}
						position++
						goto l28
					l30:
						position, tokenIndex = position28, tokenIndex28
						if buffer[position] != rune('\r') {
							goto l31
						}
						position++
						goto l28
					l31:
						position, tokenIndex = position28, tokenIndex28
						if buffer[position] != rune('\n') {
							goto l23
						}
						position++
					}
				l28:
					goto l22
				l23:
					position, tokenIndex = position23, tokenIndex23
				}
				add(rule__, position21)
			}
			return true
		l20:
			position, tokenIndex = position20, tokenIndex20
			return false
		},
		/* 3 ASSIGN <- <(_ ('-' '>') _)> */
		nil,
		/* 4 TRIQUOT <- <(_ ('"' '"' '"') _)> */
		func() bool {
			position33, tokenIndex33 := position, tokenIndex
			{
				position34 := position
				if !_rules[rule_]() {
					goto l33
				}
				if buffer[position] != rune('"') {
					goto l33
				}
				position++
				if buffer[position] != rune('"') {
					goto l33
				}
				position++
				if buffer[position] != rune('"') {
					goto l33
				}
				position++
				if !_rules[rule_]() {
					goto l33
				}
				add(ruleTRIQUOT, position34)
			}
			return true
		l33:
			position, tokenIndex = position33, tokenIndex33
			return false
		},
		/* 5 BREAK <- <(_ ('b' 'r' 'e' 'a' 'k') _)> */
		nil,
		/* 6 CLOSE <- <(_ '}' _)> */
		func() bool {
			position36, tokenIndex36 := position, tokenIndex
			{
				position37 := position
				if !_rules[rule_]() {
					goto l36
				}
				if buffer[position] != rune('}') {
					goto l36
				}
				position++
				if !_rules[rule_]() {
					goto l36
				}
				add(ruleCLOSE, position37)
			}
			return true
		l36:
			position, tokenIndex = position36, tokenIndex36
			return false
		},
		/* 7 COLON <- <(_ ':' _)> */
		nil,
		/* 8 COMMA <- <(_ ',' _)> */
		func() bool {
			position39, tokenIndex39 := position, tokenIndex
			{
				position40 := position
				if !_rules[rule_]() {
					goto l39
				}
				if buffer[position] != rune(',') {
					goto l39
				}
				position++
				if !_rules[rule_]() {
					goto l39
				}
				add(ruleCOMMA, position40)
			}
			return true
		l39:
			position, tokenIndex = position39, tokenIndex39
			return false
		},
		/* 9 COMMENT <- <(_ '#' (!'\n' .)*)> */
		nil,
		/* 10 CONT <- <(_ ('c' 'o' 'n' 't' 'i' 'n' 'u' 'e') _)> */
		nil,
		/* 11 COUNT <- <(_ ('c' 'o' 'u' 'n' 't') _)> */
		nil,
		/* 12 DECLARE <- <(_ ('d' 'e' 'c' 'l' 'a' 'r' 'e') __)> */
		nil,
		/* 13 DOT <- <'.'> */
		nil,
		/* 14 ELSE <- <(_ ('e' 'l' 's' 'e') _)> */
		func() bool {
			position46, tokenIndex46 := position, tokenIndex
			{
				position47 := position
				if !_rules[rule_]() {
					goto l46
				}
				if buffer[position] != rune('e') {
					goto l46
				}
				position++
				if buffer[position] != rune('l') {
					goto l46
				}
				position++
				if buffer[position] != rune('s') {
					goto l46
				}
				position++
				if buffer[position] != rune('e') {
					goto l46
				}
				position++
				if !_rules[rule_]() {
					goto l46
				}
				add(ruleELSE, position47)
			}
			return true
		l46:
			position, tokenIndex = position46, tokenIndex46
			return false
		},
		/* 15 IF <- <(_ ('i' 'f') _)> */
		nil,
		/* 16 IN <- <(__ ('i' 'n') __)> */
		nil,
		/* 17 INCLUDE <- <(_ ('i' 'n' 'c' 'l' 'u' 'd' 'e') __)> */
		nil,
		/* 18 LOOP <- <(_ ('l' 'o' 'o' 'p') _)> */
		nil,
		/* 19 NOOP <- <SEMI> */
		nil,
		/* 20 NOT <- <(_ ('n' 'o' 't') __)> */
		nil,
		/* 21 OPEN <- <(_ '{' _)> */
		func() bool {
			position54, tokenIndex54 := position, tokenIndex
			{
				position55 := position
				if !_rules[rule_]() {
					goto l54
				}
				if buffer[position] != rune('{') {
					goto l54
				}
				position++
				if !_rules[rule_]() {
					goto l54
				}
				add(ruleOPEN, position55)
			}
			return true
		l54:
			position, tokenIndex = position54, tokenIndex54
			return false
		},
		/* 22 SQOPEN <- <(_ '[' _)> */
		nil,
		/* 23 SQCLOSE <- <(_ ']' _)> */
		nil,
		/* 24 SCOPE <- <(':' ':')> */
		nil,
		/* 25 SEMI <- <(_ ';' _)> */
		func() bool {
			position59, tokenIndex59 := position, tokenIndex
			{
				position60 := position
				if !_rules[rule_]() {
					goto l59
				}
				if buffer[position] != rune(';') {
					goto l59
				}
				position++
				if !_rules[rule_]() {
					goto l59
				}
				add(ruleSEMI, position60)
			}
			return true
		l59:
			position, tokenIndex = position59, tokenIndex59
			return false
		},
		/* 26 SHEBANG <- <('#' '!' (!'\n' .)+ '\n')> */
		nil,
		/* 27 SKIPVAR <- <(_ '_' _)> */
		nil,
		/* 28 UNSET <- <(_ ('u' 'n' 's' 'e' 't') __)> */
		nil,
		/* 29 ScalarType <- <(Boolean / Float / Integer / String / NullValue)> */
		nil,
		/* 30 Identifier <- <(([a-z] / [A-Z] / '_') ([a-z] / [A-Z] / ([0-9] / [0-9]) / '_')*)> */
		func() bool {
			position65, tokenIndex65 := position, tokenIndex
			{
				position66 := position
				{
					position67, tokenIndex67 := position, tokenIndex
					if c := buffer[position]; c < rune('a') || c > rune('z') {
						goto l68
					}
					position++
					goto l67
				l68:
					position, tokenIndex = position67, tokenIndex67
					if c := buffer[position]; c < rune('A') || c > rune('Z') {
						goto l69
					}
					position++
					goto l67
				l69:
					position, tokenIndex = position67, tokenIndex67
					if buffer[position] != rune('_') {
						goto l65
					}
					position++
				}
			l67:
			l70:
				{
					position71, tokenIndex71 := position, tokenIndex
					{
						position72, tokenIndex72 := position, tokenIndex
						if c := buffer[position]; c < rune('a') || c > rune('z') {
							goto l73
						}
						position++
						goto l72
					l73:
						position, tokenIndex = position72, tokenIndex72
						if c := buffer[position]; c < rune('A') || c > rune('Z') {
							goto l74
						}
						position++
						goto l72
					l74:
						position, tokenIndex = position72, tokenIndex72
						{
							position76, tokenIndex76 := position, tokenIndex
							if c := buffer[position]; c < rune('0') || c > rune('9') {
								goto l77
							}
							position++
							goto l76
						l77:
							position, tokenIndex = position76, tokenIndex76
							if c := buffer[position]; c < rune('0') || c > rune('9') {
								goto l75
							}
							position++
						}
					l76:
						goto l72
					l75:
						position, tokenIndex = position72, tokenIndex72
						if buffer[position] != rune('_') {
							goto l71
						}
						position++
					}
				l72:
					goto l70
				l71:
					position, tokenIndex = position71, tokenIndex71
				}
				add(ruleIdentifier, position66)
			}
			return true
		l65:
			position, tokenIndex = position65, tokenIndex65
			return false
		},
		/* 31 Float <- <(Integer ('.' [0-9]+)?)> */
		nil,
		/* 32 Boolean <- <(('t' 'r' 'u' 'e') / ('f' 'a' 'l' 's' 'e'))> */
		nil,
		/* 33 Integer <- <('-'? PositiveInteger)> */
		func() bool {
			position80, tokenIndex80 := position, tokenIndex
			{
				position81 := position
				{
					position82, tokenIndex82 := position, tokenIndex
					if buffer[position] != rune('-') {
						goto l82
					}
					position++
					goto l83
				l82:
					position, tokenIndex = position82, tokenIndex82
				}
			l83:
				if !_rules[rulePositiveInteger]() {
					goto l80
				}
				add(ruleInteger, position81)
			}
			return true
		l80:
			position, tokenIndex = position80, tokenIndex80
			return false
		},
		/* 34 PositiveInteger <- <[0-9]+> */
		func() bool {
			position84, tokenIndex84 := position, tokenIndex
			{
				position85 := position
				if c := buffer[position]; c < rune('0') || c > rune('9') {
					goto l84
				}
				position++
			l86:
				{
					position87, tokenIndex87 := position, tokenIndex
					if c := buffer[position]; c < rune('0') || c > rune('9') {
						goto l87
					}
					position++
					goto l86
				l87:
					position, tokenIndex = position87, tokenIndex87
				}
				add(rulePositiveInteger, position85)
			}
			return true
		l84:
			position, tokenIndex = position84, tokenIndex84
			return false
		},
		/* 35 String <- <(Triquote / StringLiteral / StringInterpolated)> */
		func() bool {
			position88, tokenIndex88 := position, tokenIndex
			{
				position89 := position
				{
					position90, tokenIndex90 := position, tokenIndex
					{
						position92 := position
						if !_rules[ruleTRIQUOT]() {
							goto l91
						}
						{
							position93 := position
						l94:
							{
								position95, tokenIndex95 := position, tokenIndex
								{
									position96, tokenIndex96 := position, tokenIndex
									if !_rules[ruleTRIQUOT]() {
										goto l96
									}
									goto l95
								l96:
									position, tokenIndex = position96, tokenIndex96
								}
								if !matchDot() {
									goto l95
								}
								goto l94
							l95:
								position, tokenIndex = position95, tokenIndex95
							}
							add(ruleTriquoteBody, position93)
						}
						if !_rules[ruleTRIQUOT]() {
							goto l91
						}
						add(ruleTriquote, position92)
					}
					goto l90
				l91:
					position, tokenIndex = position90, tokenIndex90
					if !_rules[ruleStringLiteral]() {
						goto l97
					}
					goto l90
				l97:
					position, tokenIndex = position90, tokenIndex90
					if !_rules[ruleStringInterpolated]() {
						goto l88
					}
				}
			l90:
				add(ruleString, position89)
			}
			return true
		l88:
			position, tokenIndex = position88, tokenIndex88
			return false
		},
		/* 36 StringLiteral <- <('\'' (!'\'' .)* '\'')> */
		func() bool {
			position98, tokenIndex98 := position, tokenIndex
			{
				position99 := position
				if buffer[position] != rune('\'') {
					goto l98
				}
				position++
			l100:
				{
					position101, tokenIndex101 := position, tokenIndex
					{
						position102, tokenIndex102 := position, tokenIndex
						if buffer[position] != rune('\'') {
							goto l102
						}
						position++
						goto l101
					l102:
						position, tokenIndex = position102, tokenIndex102
					}
					if !matchDot() {
						goto l101
					}
					goto l100
				l101:
					position, tokenIndex = position101, tokenIndex101
				}
				if buffer[position] != rune('\'') {
					goto l98
				}
				position++
				add(ruleStringLiteral, position99)
			}
			return true
		l98:
			position, tokenIndex = position98, tokenIndex98
			return false
		},
		/* 37 StringInterpolated <- <('"' (!'"' .)* '"')> */
		func() bool {
			position103, tokenIndex103 := position, tokenIndex
			{
				position104 := position
				if buffer[position] != rune('"') {
					goto l103
				}
				position++
			l105:
				{
					position106, tokenIndex106 := position, tokenIndex
					{
						position107, tokenIndex107 := position, tokenIndex
						if buffer[position] != rune('"') {
							goto l107
						}
						position++
						goto l106
					l107:
						position, tokenIndex = position107, tokenIndex107
					}
					if !matchDot() {
						goto l106
					}
					goto l105
				l106:
					position, tokenIndex = position106, tokenIndex106
				}
				if buffer[position] != rune('"') {
					goto l103
				}
				position++
				add(ruleStringInterpolated, position104)
			}
			return true
		l103:
			position, tokenIndex = position103, tokenIndex103
			return false
		},
		/* 38 Triquote <- <(TRIQUOT TriquoteBody TRIQUOT)> */
		nil,
		/* 39 TriquoteBody <- <(!TRIQUOT .)*> */
		nil,
		/* 40 NullValue <- <('n' 'u' 'l' 'l')> */
		nil,
		/* 41 Object <- <(OPEN (_ KeyValuePair _)* CLOSE)> */
		func() bool {
			position111, tokenIndex111 := position, tokenIndex
			{
				position112 := position
				if !_rules[ruleOPEN]() {
					goto l111
				}
			l113:
				{
					position114, tokenIndex114 := position, tokenIndex
					if !_rules[rule_]() {
						goto l114
					}
					{
						position115 := position
						{
							position116 := position
							{
								position117, tokenIndex117 := position, tokenIndex
								if !_rules[ruleIdentifier]() {
									goto l118
								}
								goto l117
							l118:
								position, tokenIndex = position117, tokenIndex117
								if !_rules[ruleStringLiteral]() {
									goto l119
								}
								goto l117
							l119:
								position, tokenIndex = position117, tokenIndex117
								if !_rules[ruleStringInterpolated]() {
									goto l114
								}
							}
						l117:
							add(ruleKey, position116)
						}
						{
							position120 := position
							if !_rules[rule_]() {
								goto l114
							}
							if buffer[position] != rune(':') {
								goto l114
							}
							position++
							if !_rules[rule_]() {
								goto l114
							}
							add(ruleCOLON, position120)
						}
						{
							position121 := position
							{
								position122, tokenIndex122 := position, tokenIndex
								if !_rules[ruleArray]() {
									goto l123
								}
								goto l122
							l123:
								position, tokenIndex = position122, tokenIndex122
								if !_rules[ruleObject]() {
									goto l124
								}
								goto l122
							l124:
								position, tokenIndex = position122, tokenIndex122
								if !_rules[ruleExpression]() {
									goto l114
								}
							}
						l122:
							add(ruleKValue, position121)
						}
						{
							position125, tokenIndex125 := position, tokenIndex
							if !_rules[ruleCOMMA]() {
								goto l125
							}
							goto l126
						l125:
							position, tokenIndex = position125, tokenIndex125
						}
					l126:
						add(ruleKeyValuePair, position115)
					}
					if !_rules[rule_]() {
						goto l114
					}
					goto l113
				l114:
					position, tokenIndex = position114, tokenIndex114
				}
				if !_rules[ruleCLOSE]() {
					goto l111
				}
				add(ruleObject, position112)
			}
			return true
		l111:
			position, tokenIndex = position111, tokenIndex111
			return false
		},
		/* 42 Array <- <('[' _ ExpressionSequence COMMA? ']')> */
		func() bool {
			position127, tokenIndex127 := position, tokenIndex
			{
				position128 := position
				if buffer[position] != rune('[') {
					goto l127
				}
				position++
				if !_rules[rule_]() {
					goto l127
				}
				if !_rules[ruleExpressionSequence]() {
					goto l127
				}
				{
					position129, tokenIndex129 := position, tokenIndex
					if !_rules[ruleCOMMA]() {
						goto l129
					}
					goto l130
				l129:
					position, tokenIndex = position129, tokenIndex129
				}
			l130:
				if buffer[position] != rune(']') {
					goto l127
				}
				position++
				add(ruleArray, position128)
			}
			return true
		l127:
			position, tokenIndex = position127, tokenIndex127
			return false
		},
		/* 43 RegularExpression <- <('/' (!'/' .)+ '/' ('i' / 'l' / 'm' / 's' / 'u')*)> */
		func() bool {
			position131, tokenIndex131 := position, tokenIndex
			{
				position132 := position
				if buffer[position] != rune('/') {
					goto l131
				}
				position++
				{
					position135, tokenIndex135 := position, tokenIndex
					if buffer[position] != rune('/') {
						goto l135
					}
					position++
					goto l131
				l135:
					position, tokenIndex = position135, tokenIndex135
				}
				if !matchDot() {
					goto l131
				}
			l133:
				{
					position134, tokenIndex134 := position, tokenIndex
					{
						position136, tokenIndex136 := position, tokenIndex
						if buffer[position] != rune('/') {
							goto l136
						}
						position++
						goto l134
					l136:
						position, tokenIndex = position136, tokenIndex136
					}
					if !matchDot() {
						goto l134
					}
					goto l133
				l134:
					position, tokenIndex = position134, tokenIndex134
				}
				if buffer[position] != rune('/') {
					goto l131
				}
				position++
			l137:
				{
					position138, tokenIndex138 := position, tokenIndex
					{
						position139, tokenIndex139 := position, tokenIndex
						if buffer[position] != rune('i') {
							goto l140
						}
						position++
						goto l139
					l140:
						position, tokenIndex = position139, tokenIndex139
						if buffer[position] != rune('l') {
							goto l141
						}
						position++
						goto l139
					l141:
						position, tokenIndex = position139, tokenIndex139
						if buffer[position] != rune('m') {
							goto l142
						}
						position++
						goto l139
					l142:
						position, tokenIndex = position139, tokenIndex139
						if buffer[position] != rune('s') {
							goto l143
						}
						position++
						goto l139
					l143:
						position, tokenIndex = position139, tokenIndex139
						if buffer[position] != rune('u') {
							goto l138
						}
						position++
					}
				l139:
					goto l137
				l138:
					position, tokenIndex = position138, tokenIndex138
				}
				add(ruleRegularExpression, position132)
			}
			return true
		l131:
			position, tokenIndex = position131, tokenIndex131
			return false
		},
		/* 44 KeyValuePair <- <(Key COLON KValue COMMA?)> */
		nil,
		/* 45 Key <- <(Identifier / StringLiteral / StringInterpolated)> */
		nil,
		/* 46 KValue <- <(Array / Object / Expression)> */
		nil,
		/* 47 Type <- <(Array / Object / RegularExpression / ScalarType)> */
		func() bool {
			position147, tokenIndex147 := position, tokenIndex
			{
				position148 := position
				{
					position149, tokenIndex149 := position, tokenIndex
					if !_rules[ruleArray]() {
						goto l150
					}
					goto l149
				l150:
					position, tokenIndex = position149, tokenIndex149
					if !_rules[ruleObject]() {
						goto l151
					}
					goto l149
				l151:
					position, tokenIndex = position149, tokenIndex149
					if !_rules[ruleRegularExpression]() {
						goto l152
					}
					goto l149
				l152:
					position, tokenIndex = position149, tokenIndex149
					{
						position153 := position
						{
							position154, tokenIndex154 := position, tokenIndex
							{
								position156 := position
								{
									position157, tokenIndex157 := position, tokenIndex
									if buffer[position] != rune('t') {
										goto l158
									}
									position++
									if buffer[position] != rune('r') {
										goto l158
									}
									position++
									if buffer[position] != rune('u') {
										goto l158
									}
									position++
									if buffer[position] != rune('e') {
										goto l158
									}
									position++
									goto l157
								l158:
									position, tokenIndex = position157, tokenIndex157
									if buffer[position] != rune('f') {
										goto l155
									}
									position++
									if buffer[position] != rune('a') {
										goto l155
									}
									position++
									if buffer[position] != rune('l') {
										goto l155
									}
									position++
									if buffer[position] != rune('s') {
										goto l155
									}
									position++
									if buffer[position] != rune('e') {
										goto l155
									}
									position++
								}
							l157:
								add(ruleBoolean, position156)
							}
							goto l154
						l155:
							position, tokenIndex = position154, tokenIndex154
							{
								position160 := position
								if !_rules[ruleInteger]() {
									goto l159
								}
								{
									position161, tokenIndex161 := position, tokenIndex
									if buffer[position] != rune('.') {
										goto l161
									}
									position++
									if c := buffer[position]; c < rune('0') || c > rune('9') {
										goto l161
									}
									position++
								l163:
									{
										position164, tokenIndex164 := position, tokenIndex
										if c := buffer[position]; c < rune('0') || c > rune('9') {
											goto l164
										}
										position++
										goto l163
									l164:
										position, tokenIndex = position164, tokenIndex164
									}
									goto l162
								l161:
									position, tokenIndex = position161, tokenIndex161
								}
							l162:
								add(ruleFloat, position160)
							}
							goto l154
						l159:
							position, tokenIndex = position154, tokenIndex154
							if !_rules[ruleInteger]() {
								goto l165
							}
							goto l154
						l165:
							position, tokenIndex = position154, tokenIndex154
							if !_rules[ruleString]() {
								goto l166
							}
							goto l154
						l166:
							position, tokenIndex = position154, tokenIndex154
							{
								position167 := position
								if buffer[position] != rune('n') {
									goto l147
								}
								position++
								if buffer[position] != rune('u') {
									goto l147
								}
								position++
								if buffer[position] != rune('l') {
									goto l147
								}
								position++
								if buffer[position] != rune('l') {
									goto l147
								}
								position++
								add(ruleNullValue, position167)
							}
						}
					l154:
						add(ruleScalarType, position153)
					}
				}
			l149:
				add(ruleType, position148)
			}
			return true
		l147:
			position, tokenIndex = position147, tokenIndex147
			return false
		},
		/* 48 Exponentiate <- <(_ ('*' '*') _)> */
		nil,
		/* 49 Multiply <- <(_ '*' _)> */
		nil,
		/* 50 Divide <- <(_ '/' _)> */
		nil,
		/* 51 Modulus <- <(_ '%' _)> */
		nil,
		/* 52 Add <- <(_ '+' _)> */
		nil,
		/* 53 Subtract <- <(_ '-' _)> */
		nil,
		/* 54 BitwiseAnd <- <(_ '&' _)> */
		nil,
		/* 55 BitwiseOr <- <(_ '|' _)> */
		nil,
		/* 56 BitwiseNot <- <(_ '~' _)> */
		nil,
		/* 57 BitwiseXor <- <(_ '^' _)> */
		nil,
		/* 58 MatchOperator <- <(Match / Unmatch)> */
		nil,
		/* 59 Unmatch <- <(_ ('!' '~') _)> */
		nil,
		/* 60 Match <- <(_ ('=' '~') _)> */
		nil,
		/* 61 Operator <- <(_ (Exponentiate / Multiply / Divide / Modulus / Add / Subtract / BitwiseAnd / BitwiseOr / BitwiseNot / BitwiseXor) _)> */
		nil,
		/* 62 AssignmentOperator <- <(_ (AssignEq / StarEq / DivEq / PlusEq / MinusEq / AndEq / OrEq / Append) _)> */
		nil,
		/* 63 AssignEq <- <(_ '=' _)> */
		nil,
		/* 64 StarEq <- <(_ ('*' '=') _)> */
		nil,
		/* 65 DivEq <- <(_ ('/' '=') _)> */
		nil,
		/* 66 PlusEq <- <(_ ('+' '=') _)> */
		nil,
		/* 67 MinusEq <- <(_ ('-' '=') _)> */
		nil,
		/* 68 AndEq <- <(_ ('&' '=') _)> */
		nil,
		/* 69 OrEq <- <(_ ('|' '=') _)> */
		nil,
		/* 70 Append <- <(_ ('<' '<') _)> */
		nil,
		/* 71 ComparisonOperator <- <(_ (Equality / NonEquality / GreaterEqual / LessEqual / GreaterThan / LessThan / Membership / NonMembership) _)> */
		nil,
		/* 72 Equality <- <(_ ('=' '=') _)> */
		nil,
		/* 73 NonEquality <- <(_ ('!' '=') _)> */
		nil,
		/* 74 GreaterThan <- <(_ '>' _)> */
		nil,
		/* 75 GreaterEqual <- <(_ ('>' '=') _)> */
		nil,
		/* 76 LessEqual <- <(_ ('<' '=') _)> */
		nil,
		/* 77 LessThan <- <(_ '<' _)> */
		nil,
		/* 78 Membership <- <(_ ('i' 'n') _)> */
		nil,
		/* 79 NonMembership <- <(_ ('n' 'o' 't') __ ('i' 'n') _)> */
		nil,
		/* 80 Variable <- <(('$' VariableNameSequence) / SKIPVAR)> */
		func() bool {
			position200, tokenIndex200 := position, tokenIndex
			{
				position201 := position
				{
					position202, tokenIndex202 := position, tokenIndex
					if buffer[position] != rune('$') {
						goto l203
					}
					position++
					{
						position204 := position
					l205:
						{
							position206, tokenIndex206 := position, tokenIndex
							if !_rules[ruleVariableName]() {
								goto l206
							}
							{
								position207 := position
								if buffer[position] != rune('.') {
									goto l206
								}
								position++
								add(ruleDOT, position207)
							}
							goto l205
						l206:
							position, tokenIndex = position206, tokenIndex206
						}
						if !_rules[ruleVariableName]() {
							goto l203
						}
						add(ruleVariableNameSequence, position204)
					}
					goto l202
				l203:
					position, tokenIndex = position202, tokenIndex202
					{
						position208 := position
						if !_rules[rule_]() {
							goto l200
						}
						if buffer[position] != rune('_') {
							goto l200
						}
						position++
						if !_rules[rule_]() {
							goto l200
						}
						add(ruleSKIPVAR, position208)
					}
				}
			l202:
				add(ruleVariable, position201)
			}
			return true
		l200:
			position, tokenIndex = position200, tokenIndex200
			return false
		},
		/* 81 VariableNameSequence <- <((VariableName DOT)* VariableName)> */
		nil,
		/* 82 VariableName <- <(Identifier ('[' _ VariableIndex _ ']')?)> */
		func() bool {
			position210, tokenIndex210 := position, tokenIndex
			{
				position211 := position
				if !_rules[ruleIdentifier]() {
					goto l210
				}
				{
					position212, tokenIndex212 := position, tokenIndex
					if buffer[position] != rune('[') {
						goto l212
					}
					position++
					if !_rules[rule_]() {
						goto l212
					}
					{
						position214 := position
						if !_rules[ruleExpression]() {
							goto l212
						}
						add(ruleVariableIndex, position214)
					}
					if !_rules[rule_]() {
						goto l212
					}
					if buffer[position] != rune(']') {
						goto l212
					}
					position++
					goto l213
				l212:
					position, tokenIndex = position212, tokenIndex212
				}
			l213:
				add(ruleVariableName, position211)
			}
			return true
		l210:
			position, tokenIndex = position210, tokenIndex210
			return false
		},
		/* 83 VariableIndex <- <Expression> */
		nil,
		/* 84 Block <- <(_ (COMMENT / FlowControlWord / StatementBlock) SEMI? _)> */
		func() bool {
			position216, tokenIndex216 := position, tokenIndex
			{
				position217 := position
				if !_rules[rule_]() {
					goto l216
				}
				{
					position218, tokenIndex218 := position, tokenIndex
					{
						position220 := position
						if !_rules[rule_]() {
							goto l219
						}
						if buffer[position] != rune('#') {
							goto l219
						}
						position++
					l221:
						{
							position222, tokenIndex222 := position, tokenIndex
							{
								position223, tokenIndex223 := position, tokenIndex
								if buffer[position] != rune('\n') {
									goto l223
								}
								position++
								goto l222
							l223:
								position, tokenIndex = position223, tokenIndex223
							}
							if !matchDot() {
								goto l222
							}
							goto l221
						l222:
							position, tokenIndex = position222, tokenIndex222
						}
						add(ruleCOMMENT, position220)
					}
					goto l218
				l219:
					position, tokenIndex = position218, tokenIndex218
					{
						position225 := position
						{
							position226, tokenIndex226 := position, tokenIndex
							{
								position228 := position
								{
									position229 := position
									if !_rules[rule_]() {
										goto l227
									}
									if buffer[position] != rune('b') {
										goto l227
									}
									position++
									if buffer[position] != rune('r') {
										goto l227
									}
									position++
									if buffer[position] != rune('e') {
										goto l227
									}
									position++
									if buffer[position] != rune('a') {
										goto l227
									}
									position++
									if buffer[position] != rune('k') {
										goto l227
									}
									position++
									if !_rules[rule_]() {
										goto l227
									}
									add(ruleBREAK, position229)
								}
								{
									position230, tokenIndex230 := position, tokenIndex
									if !_rules[rulePositiveInteger]() {
										goto l230
									}
									goto l231
								l230:
									position, tokenIndex = position230, tokenIndex230
								}
							l231:
								add(ruleFlowControlBreak, position228)
							}
							goto l226
						l227:
							position, tokenIndex = position226, tokenIndex226
							{
								position232 := position
								{
									position233 := position
									if !_rules[rule_]() {
										goto l224
									}
									if buffer[position] != rune('c') {
										goto l224
									}
									position++
									if buffer[position] != rune('o') {
										goto l224
									}
									position++
									if buffer[position] != rune('n') {
										goto l224
									}
									position++
									if buffer[position] != rune('t') {
										goto l224
									}
									position++
									if buffer[position] != rune('i') {
										goto l224
									}
									position++
									if buffer[position] != rune('n') {
										goto l224
									}
									position++
									if buffer[position] != rune('u') {
										goto l224
									}
									position++
									if buffer[position] != rune('e') {
										goto l224
									}
									position++
									if !_rules[rule_]() {
										goto l224
									}
									add(ruleCONT, position233)
								}
								{
									position234, tokenIndex234 := position, tokenIndex
									if !_rules[rulePositiveInteger]() {
										goto l234
									}
									goto l235
								l234:
									position, tokenIndex = position234, tokenIndex234
								}
							l235:
								add(ruleFlowControlContinue, position232)
							}
						}
					l226:
						add(ruleFlowControlWord, position225)
					}
					goto l218
				l224:
					position, tokenIndex = position218, tokenIndex218
					{
						position236 := position
						{
							position237, tokenIndex237 := position, tokenIndex
							{
								position239 := position
								if !_rules[ruleSEMI]() {
									goto l238
								}
								add(ruleNOOP, position239)
							}
							goto l237
						l238:
							position, tokenIndex = position237, tokenIndex237
							if !_rules[ruleAssignment]() {
								goto l240
							}
							goto l237
						l240:
							position, tokenIndex = position237, tokenIndex237
							{
								position242 := position
								{
									position243, tokenIndex243 := position, tokenIndex
									{
										position245 := position
										{
											position246 := position
											if !_rules[rule_]() {
												goto l244
											}
											if buffer[position] != rune('u') {
												goto l244
											}
											position++
											if buffer[position] != rune('n') {
												goto l244
											}
											position++
											if buffer[position] != rune('s') {
												goto l244
											}
											position++
											if buffer[position] != rune('e') {
												goto l244
											}
											position++
											if buffer[position] != rune('t') {
												goto l244
											}
											position++
											if !_rules[rule__]() {
												goto l244
											}
											add(ruleUNSET, position246)
										}
										if !_rules[ruleVariableSequence]() {
											goto l244
										}
										add(ruleDirectiveUnset, position245)
									}
									goto l243
								l244:
									position, tokenIndex = position243, tokenIndex243
									{
										position248 := position
										{
											position249 := position
											if !_rules[rule_]() {
												goto l247
											}
											if buffer[position] != rune('i') {
												goto l247
											}
											position++
											if buffer[position] != rune('n') {
												goto l247
											}
											position++
											if buffer[position] != rune('c') {
												goto l247
											}
											position++
											if buffer[position] != rune('l') {
												goto l247
											}
											position++
											if buffer[position] != rune('u') {
												goto l247
											}
											position++
											if buffer[position] != rune('d') {
												goto l247
											}
											position++
											if buffer[position] != rune('e') {
												goto l247
											}
											position++
											if !_rules[rule__]() {
												goto l247
											}
											add(ruleINCLUDE, position249)
										}
										if !_rules[ruleString]() {
											goto l247
										}
										add(ruleDirectiveInclude, position248)
									}
									goto l243
								l247:
									position, tokenIndex = position243, tokenIndex243
									{
										position250 := position
										{
											position251 := position
											if !_rules[rule_]() {
												goto l241
											}
											if buffer[position] != rune('d') {
												goto l241
											}
											position++
											if buffer[position] != rune('e') {
												goto l241
											}
											position++
											if buffer[position] != rune('c') {
												goto l241
											}
											position++
											if buffer[position] != rune('l') {
												goto l241
											}
											position++
											if buffer[position] != rune('a') {
												goto l241
											}
											position++
											if buffer[position] != rune('r') {
												goto l241
											}
											position++
											if buffer[position] != rune('e') {
												goto l241
											}
											position++
											if !_rules[rule__]() {
												goto l241
											}
											add(ruleDECLARE, position251)
										}
										if !_rules[ruleVariableSequence]() {
											goto l241
										}
										add(ruleDirectiveDeclare, position250)
									}
								}
							l243:
								add(ruleDirective, position242)
							}
							goto l237
						l241:
							position, tokenIndex = position237, tokenIndex237
							{
								position253 := position
								if !_rules[ruleIfStanza]() {
									goto l252
								}
							l254:
								{
									position255, tokenIndex255 := position, tokenIndex
									{
										position256 := position
										if !_rules[ruleELSE]() {
											goto l255
										}
										if !_rules[ruleIfStanza]() {
											goto l255
										}
										add(ruleElseIfStanza, position256)
									}
									goto l254
								l255:
									position, tokenIndex = position255, tokenIndex255
								}
								{
									position257, tokenIndex257 := position, tokenIndex
									{
										position259 := position
										if !_rules[ruleELSE]() {
											goto l257
										}
										if !_rules[ruleOPEN]() {
											goto l257
										}
									l260:
										{
											position261, tokenIndex261 := position, tokenIndex
											if !_rules[ruleBlock]() {
												goto l261
											}
											goto l260
										l261:
											position, tokenIndex = position261, tokenIndex261
										}
										if !_rules[ruleCLOSE]() {
											goto l257
										}
										add(ruleElseStanza, position259)
									}
									goto l258
								l257:
									position, tokenIndex = position257, tokenIndex257
								}
							l258:
								add(ruleConditional, position253)
							}
							goto l237
						l252:
							position, tokenIndex = position237, tokenIndex237
							{
								position263 := position
								{
									position264 := position
									if !_rules[rule_]() {
										goto l262
									}
									if buffer[position] != rune('l') {
										goto l262
									}
									position++
									if buffer[position] != rune('o') {
										goto l262
									}
									position++
									if buffer[position] != rune('o') {
										goto l262
									}
									position++
									if buffer[position] != rune('p') {
										goto l262
									}
									position++
									if !_rules[rule_]() {
										goto l262
									}
									add(ruleLOOP, position264)
								}
								{
									position265, tokenIndex265 := position, tokenIndex
									if !_rules[ruleOPEN]() {
										goto l266
									}
								l267:
									{
										position268, tokenIndex268 := position, tokenIndex
										if !_rules[ruleBlock]() {
											goto l268
										}
										goto l267
									l268:
										position, tokenIndex = position268, tokenIndex268
									}
									if !_rules[ruleCLOSE]() {
										goto l266
									}
									goto l265
								l266:
									position, tokenIndex = position265, tokenIndex265
									{
										position270 := position
										{
											position271 := position
											if !_rules[rule_]() {
												goto l269
											}
											if buffer[position] != rune('c') {
												goto l269
											}
											position++
											if buffer[position] != rune('o') {
												goto l269
											}
											position++
											if buffer[position] != rune('u') {
												goto l269
											}
											position++
											if buffer[position] != rune('n') {
												goto l269
											}
											position++
											if buffer[position] != rune('t') {
												goto l269
											}
											position++
											if !_rules[rule_]() {
												goto l269
											}
											add(ruleCOUNT, position271)
										}
										{
											position272, tokenIndex272 := position, tokenIndex
											if !_rules[ruleInteger]() {
												goto l273
											}
											goto l272
										l273:
											position, tokenIndex = position272, tokenIndex272
											if !_rules[ruleVariable]() {
												goto l269
											}
										}
									l272:
										add(ruleLoopConditionFixedLength, position270)
									}
									if !_rules[ruleOPEN]() {
										goto l269
									}
								l274:
									{
										position275, tokenIndex275 := position, tokenIndex
										if !_rules[ruleBlock]() {
											goto l275
										}
										goto l274
									l275:
										position, tokenIndex = position275, tokenIndex275
									}
									if !_rules[ruleCLOSE]() {
										goto l269
									}
									goto l265
								l269:
									position, tokenIndex = position265, tokenIndex265
									{
										position277 := position
										{
											position278 := position
											if !_rules[ruleVariableSequence]() {
												goto l276
											}
											add(ruleLoopIterableLHS, position278)
										}
										{
											position279 := position
											if !_rules[rule__]() {
												goto l276
											}
											if buffer[position] != rune('i') {
												goto l276
											}
											position++
											if buffer[position] != rune('n') {
												goto l276
											}
											position++
											if !_rules[rule__]() {
												goto l276
											}
											add(ruleIN, position279)
										}
										{
											position280 := position
											{
												position281, tokenIndex281 := position, tokenIndex
												if !_rules[ruleCommand]() {
													goto l282
												}
												goto l281
											l282:
												position, tokenIndex = position281, tokenIndex281
												if !_rules[ruleVariable]() {
													goto l276
												}
											}
										l281:
											add(ruleLoopIterableRHS, position280)
										}
										add(ruleLoopConditionIterable, position277)
									}
									if !_rules[ruleOPEN]() {
										goto l276
									}
								l283:
									{
										position284, tokenIndex284 := position, tokenIndex
										if !_rules[ruleBlock]() {
											goto l284
										}
										goto l283
									l284:
										position, tokenIndex = position284, tokenIndex284
									}
									if !_rules[ruleCLOSE]() {
										goto l276
									}
									goto l265
								l276:
									position, tokenIndex = position265, tokenIndex265
									{
										position286 := position
										if !_rules[ruleCommand]() {
											goto l285
										}
										if !_rules[ruleSEMI]() {
											goto l285
										}
										if !_rules[ruleConditionalExpression]() {
											goto l285
										}
										if !_rules[ruleSEMI]() {
											goto l285
										}
										if !_rules[ruleCommand]() {
											goto l285
										}
										add(ruleLoopConditionBounded, position286)
									}
									if !_rules[ruleOPEN]() {
										goto l285
									}
								l287:
									{
										position288, tokenIndex288 := position, tokenIndex
										if !_rules[ruleBlock]() {
											goto l288
										}
										goto l287
									l288:
										position, tokenIndex = position288, tokenIndex288
									}
									if !_rules[ruleCLOSE]() {
										goto l285
									}
									goto l265
								l285:
									position, tokenIndex = position265, tokenIndex265
									{
										position289 := position
										if !_rules[ruleConditionalExpression]() {
											goto l262
										}
										add(ruleLoopConditionTruthy, position289)
									}
									if !_rules[ruleOPEN]() {
										goto l262
									}
								l290:
									{
										position291, tokenIndex291 := position, tokenIndex
										if !_rules[ruleBlock]() {
											goto l291
										}
										goto l290
									l291:
										position, tokenIndex = position291, tokenIndex291
									}
									if !_rules[ruleCLOSE]() {
										goto l262
									}
								}
							l265:
								add(ruleLoop, position263)
							}
							goto l237
						l262:
							position, tokenIndex = position237, tokenIndex237
							if !_rules[ruleCommand]() {
								goto l216
							}
						}
					l237:
						add(ruleStatementBlock, position236)
					}
				}
			l218:
				{
					position292, tokenIndex292 := position, tokenIndex
					if !_rules[ruleSEMI]() {
						goto l292
					}
					goto l293
				l292:
					position, tokenIndex = position292, tokenIndex292
				}
			l293:
				if !_rules[rule_]() {
					goto l216
				}
				add(ruleBlock, position217)
			}
			return true
		l216:
			position, tokenIndex = position216, tokenIndex216
			return false
		},
		/* 85 FlowControlWord <- <(FlowControlBreak / FlowControlContinue)> */
		nil,
		/* 86 FlowControlBreak <- <(BREAK PositiveInteger?)> */
		nil,
		/* 87 FlowControlContinue <- <(CONT PositiveInteger?)> */
		nil,
		/* 88 StatementBlock <- <(NOOP / Assignment / Directive / Conditional / Loop / Command)> */
		nil,
		/* 89 Assignment <- <(AssignmentLHS AssignmentOperator AssignmentRHS)> */
		func() bool {
			position298, tokenIndex298 := position, tokenIndex
			{
				position299 := position
				{
					position300 := position
					if !_rules[ruleVariableSequence]() {
						goto l298
					}
					add(ruleAssignmentLHS, position300)
				}
				{
					position301 := position
					if !_rules[rule_]() {
						goto l298
					}
					{
						position302, tokenIndex302 := position, tokenIndex
						{
							position304 := position
							if !_rules[rule_]() {
								goto l303
							}
							if buffer[position] != rune('=') {
								goto l303
							}
							position++
							if !_rules[rule_]() {
								goto l303
							}
							add(ruleAssignEq, position304)
						}
						goto l302
					l303:
						position, tokenIndex = position302, tokenIndex302
						{
							position306 := position
							if !_rules[rule_]() {
								goto l305
							}
							if buffer[position] != rune('*') {
								goto l305
							}
							position++
							if buffer[position] != rune('=') {
								goto l305
							}
							position++
							if !_rules[rule_]() {
								goto l305
							}
							add(ruleStarEq, position306)
						}
						goto l302
					l305:
						position, tokenIndex = position302, tokenIndex302
						{
							position308 := position
							if !_rules[rule_]() {
								goto l307
							}
							if buffer[position] != rune('/') {
								goto l307
							}
							position++
							if buffer[position] != rune('=') {
								goto l307
							}
							position++
							if !_rules[rule_]() {
								goto l307
							}
							add(ruleDivEq, position308)
						}
						goto l302
					l307:
						position, tokenIndex = position302, tokenIndex302
						{
							position310 := position
							if !_rules[rule_]() {
								goto l309
							}
							if buffer[position] != rune('+') {
								goto l309
							}
							position++
							if buffer[position] != rune('=') {
								goto l309
							}
							position++
							if !_rules[rule_]() {
								goto l309
							}
							add(rulePlusEq, position310)
						}
						goto l302
					l309:
						position, tokenIndex = position302, tokenIndex302
						{
							position312 := position
							if !_rules[rule_]() {
								goto l311
							}
							if buffer[position] != rune('-') {
								goto l311
							}
							position++
							if buffer[position] != rune('=') {
								goto l311
							}
							position++
							if !_rules[rule_]() {
								goto l311
							}
							add(ruleMinusEq, position312)
						}
						goto l302
					l311:
						position, tokenIndex = position302, tokenIndex302
						{
							position314 := position
							if !_rules[rule_]() {
								goto l313
							}
							if buffer[position] != rune('&') {
								goto l313
							}
							position++
							if buffer[position] != rune('=') {
								goto l313
							}
							position++
							if !_rules[rule_]() {
								goto l313
							}
							add(ruleAndEq, position314)
						}
						goto l302
					l313:
						position, tokenIndex = position302, tokenIndex302
						{
							position316 := position
							if !_rules[rule_]() {
								goto l315
							}
							if buffer[position] != rune('|') {
								goto l315
							}
							position++
							if buffer[position] != rune('=') {
								goto l315
							}
							position++
							if !_rules[rule_]() {
								goto l315
							}
							add(ruleOrEq, position316)
						}
						goto l302
					l315:
						position, tokenIndex = position302, tokenIndex302
						{
							position317 := position
							if !_rules[rule_]() {
								goto l298
							}
							if buffer[position] != rune('<') {
								goto l298
							}
							position++
							if buffer[position] != rune('<') {
								goto l298
							}
							position++
							if !_rules[rule_]() {
								goto l298
							}
							add(ruleAppend, position317)
						}
					}
				l302:
					if !_rules[rule_]() {
						goto l298
					}
					add(ruleAssignmentOperator, position301)
				}
				{
					position318 := position
					if !_rules[ruleExpressionSequence]() {
						goto l298
					}
					add(ruleAssignmentRHS, position318)
				}
				add(ruleAssignment, position299)
			}
			return true
		l298:
			position, tokenIndex = position298, tokenIndex298
			return false
		},
		/* 90 AssignmentLHS <- <VariableSequence> */
		nil,
		/* 91 AssignmentRHS <- <ExpressionSequence> */
		nil,
		/* 92 VariableSequence <- <((Variable COMMA)* Variable)> */
		func() bool {
			position321, tokenIndex321 := position, tokenIndex
			{
				position322 := position
			l323:
				{
					position324, tokenIndex324 := position, tokenIndex
					if !_rules[ruleVariable]() {
						goto l324
					}
					if !_rules[ruleCOMMA]() {
						goto l324
					}
					goto l323
				l324:
					position, tokenIndex = position324, tokenIndex324
				}
				if !_rules[ruleVariable]() {
					goto l321
				}
				add(ruleVariableSequence, position322)
			}
			return true
		l321:
			position, tokenIndex = position321, tokenIndex321
			return false
		},
		/* 93 ExpressionSequence <- <((Expression COMMA)* Expression)> */
		func() bool {
			position325, tokenIndex325 := position, tokenIndex
			{
				position326 := position
			l327:
				{
					position328, tokenIndex328 := position, tokenIndex
					if !_rules[ruleExpression]() {
						goto l328
					}
					if !_rules[ruleCOMMA]() {
						goto l328
					}
					goto l327
				l328:
					position, tokenIndex = position328, tokenIndex328
				}
				if !_rules[ruleExpression]() {
					goto l325
				}
				add(ruleExpressionSequence, position326)
			}
			return true
		l325:
			position, tokenIndex = position325, tokenIndex325
			return false
		},
		/* 94 Expression <- <(_ ExpressionLHS ExpressionRHS? _)> */
		func() bool {
			position329, tokenIndex329 := position, tokenIndex
			{
				position330 := position
				if !_rules[rule_]() {
					goto l329
				}
				{
					position331 := position
					{
						position332 := position
						{
							position333, tokenIndex333 := position, tokenIndex
							if !_rules[ruleType]() {
								goto l334
							}
							goto l333
						l334:
							position, tokenIndex = position333, tokenIndex333
							if !_rules[ruleVariable]() {
								goto l329
							}
						}
					l333:
						add(ruleValueYielding, position332)
					}
					add(ruleExpressionLHS, position331)
				}
				{
					position335, tokenIndex335 := position, tokenIndex
					{
						position337 := position
						{
							position338 := position
							if !_rules[rule_]() {
								goto l335
							}
							{
								position339, tokenIndex339 := position, tokenIndex
								{
									position341 := position
									if !_rules[rule_]() {
										goto l340
									}
									if buffer[position] != rune('*') {
										goto l340
									}
									position++
									if buffer[position] != rune('*') {
										goto l340
									}
									position++
									if !_rules[rule_]() {
										goto l340
									}
									add(ruleExponentiate, position341)
								}
								goto l339
							l340:
								position, tokenIndex = position339, tokenIndex339
								{
									position343 := position
									if !_rules[rule_]() {
										goto l342
									}
									if buffer[position] != rune('*') {
										goto l342
									}
									position++
									if !_rules[rule_]() {
										goto l342
									}
									add(ruleMultiply, position343)
								}
								goto l339
							l342:
								position, tokenIndex = position339, tokenIndex339
								{
									position345 := position
									if !_rules[rule_]() {
										goto l344
									}
									if buffer[position] != rune('/') {
										goto l344
									}
									position++
									if !_rules[rule_]() {
										goto l344
									}
									add(ruleDivide, position345)
								}
								goto l339
							l344:
								position, tokenIndex = position339, tokenIndex339
								{
									position347 := position
									if !_rules[rule_]() {
										goto l346
									}
									if buffer[position] != rune('%') {
										goto l346
									}
									position++
									if !_rules[rule_]() {
										goto l346
									}
									add(ruleModulus, position347)
								}
								goto l339
							l346:
								position, tokenIndex = position339, tokenIndex339
								{
									position349 := position
									if !_rules[rule_]() {
										goto l348
									}
									if buffer[position] != rune('+') {
										goto l348
									}
									position++
									if !_rules[rule_]() {
										goto l348
									}
									add(ruleAdd, position349)
								}
								goto l339
							l348:
								position, tokenIndex = position339, tokenIndex339
								{
									position351 := position
									if !_rules[rule_]() {
										goto l350
									}
									if buffer[position] != rune('-') {
										goto l350
									}
									position++
									if !_rules[rule_]() {
										goto l350
									}
									add(ruleSubtract, position351)
								}
								goto l339
							l350:
								position, tokenIndex = position339, tokenIndex339
								{
									position353 := position
									if !_rules[rule_]() {
										goto l352
									}
									if buffer[position] != rune('&') {
										goto l352
									}
									position++
									if !_rules[rule_]() {
										goto l352
									}
									add(ruleBitwiseAnd, position353)
								}
								goto l339
							l352:
								position, tokenIndex = position339, tokenIndex339
								{
									position355 := position
									if !_rules[rule_]() {
										goto l354
									}
									if buffer[position] != rune('|') {
										goto l354
									}
									position++
									if !_rules[rule_]() {
										goto l354
									}
									add(ruleBitwiseOr, position355)
								}
								goto l339
							l354:
								position, tokenIndex = position339, tokenIndex339
								{
									position357 := position
									if !_rules[rule_]() {
										goto l356
									}
									if buffer[position] != rune('~') {
										goto l356
									}
									position++
									if !_rules[rule_]() {
										goto l356
									}
									add(ruleBitwiseNot, position357)
								}
								goto l339
							l356:
								position, tokenIndex = position339, tokenIndex339
								{
									position358 := position
									if !_rules[rule_]() {
										goto l335
									}
									if buffer[position] != rune('^') {
										goto l335
									}
									position++
									if !_rules[rule_]() {
										goto l335
									}
									add(ruleBitwiseXor, position358)
								}
							}
						l339:
							if !_rules[rule_]() {
								goto l335
							}
							add(ruleOperator, position338)
						}
						if !_rules[ruleExpression]() {
							goto l335
						}
						add(ruleExpressionRHS, position337)
					}
					goto l336
				l335:
					position, tokenIndex = position335, tokenIndex335
				}
			l336:
				if !_rules[rule_]() {
					goto l329
				}
				add(ruleExpression, position330)
			}
			return true
		l329:
			position, tokenIndex = position329, tokenIndex329
			return false
		},
		/* 95 ExpressionLHS <- <ValueYielding> */
		nil,
		/* 96 ExpressionRHS <- <(Operator Expression)> */
		nil,
		/* 97 InlineCommand <- <(SQOPEN Command SQCLOSE)> */
		nil,
		/* 98 ValueYielding <- <(Type / Variable)> */
		nil,
		/* 99 Directive <- <(DirectiveUnset / DirectiveInclude / DirectiveDeclare)> */
		nil,
		/* 100 DirectiveUnset <- <(UNSET VariableSequence)> */
		nil,
		/* 101 DirectiveInclude <- <(INCLUDE String)> */
		nil,
		/* 102 DirectiveDeclare <- <(DECLARE VariableSequence)> */
		nil,
		/* 103 Command <- <(_ CommandName (__ ((CommandFirstArg __ CommandSecondArg) / CommandFirstArg / CommandSecondArg))? (_ CommandResultAssignment)?)> */
		func() bool {
			position367, tokenIndex367 := position, tokenIndex
			{
				position368 := position
				if !_rules[rule_]() {
					goto l367
				}
				{
					position369 := position
					{
						position370, tokenIndex370 := position, tokenIndex
						if !_rules[ruleIdentifier]() {
							goto l370
						}
						{
							position372 := position
							if buffer[position] != rune(':') {
								goto l370
							}
							position++
							if buffer[position] != rune(':') {
								goto l370
							}
							position++
							add(ruleSCOPE, position372)
						}
						goto l371
					l370:
						position, tokenIndex = position370, tokenIndex370
					}
				l371:
					if !_rules[ruleIdentifier]() {
						goto l367
					}
					add(ruleCommandName, position369)
				}
				{
					position373, tokenIndex373 := position, tokenIndex
					if !_rules[rule__]() {
						goto l373
					}
					{
						position375, tokenIndex375 := position, tokenIndex
						if !_rules[ruleCommandFirstArg]() {
							goto l376
						}
						if !_rules[rule__]() {
							goto l376
						}
						if !_rules[ruleCommandSecondArg]() {
							goto l376
						}
						goto l375
					l376:
						position, tokenIndex = position375, tokenIndex375
						if !_rules[ruleCommandFirstArg]() {
							goto l377
						}
						goto l375
					l377:
						position, tokenIndex = position375, tokenIndex375
						if !_rules[ruleCommandSecondArg]() {
							goto l373
						}
					}
				l375:
					goto l374
				l373:
					position, tokenIndex = position373, tokenIndex373
				}
			l374:
				{
					position378, tokenIndex378 := position, tokenIndex
					if !_rules[rule_]() {
						goto l378
					}
					{
						position380 := position
						{
							position381 := position
							if !_rules[rule_]() {
								goto l378
							}
							if buffer[position] != rune('-') {
								goto l378
							}
							position++
							if buffer[position] != rune('>') {
								goto l378
							}
							position++
							if !_rules[rule_]() {
								goto l378
							}
							add(ruleASSIGN, position381)
						}
						if !_rules[ruleVariable]() {
							goto l378
						}
						add(ruleCommandResultAssignment, position380)
					}
					goto l379
				l378:
					position, tokenIndex = position378, tokenIndex378
				}
			l379:
				add(ruleCommand, position368)
			}
			return true
		l367:
			position, tokenIndex = position367, tokenIndex367
			return false
		},
		/* 104 CommandName <- <((Identifier SCOPE)? Identifier)> */
		nil,
		/* 105 CommandFirstArg <- <(Variable / Type)> */
		func() bool {
			position383, tokenIndex383 := position, tokenIndex
			{
				position384 := position
				{
					position385, tokenIndex385 := position, tokenIndex
					if !_rules[ruleVariable]() {
						goto l386
					}
					goto l385
				l386:
					position, tokenIndex = position385, tokenIndex385
					if !_rules[ruleType]() {
						goto l383
					}
				}
			l385:
				add(ruleCommandFirstArg, position384)
			}
			return true
		l383:
			position, tokenIndex = position383, tokenIndex383
			return false
		},
		/* 106 CommandSecondArg <- <Object> */
		func() bool {
			position387, tokenIndex387 := position, tokenIndex
			{
				position388 := position
				if !_rules[ruleObject]() {
					goto l387
				}
				add(ruleCommandSecondArg, position388)
			}
			return true
		l387:
			position, tokenIndex = position387, tokenIndex387
			return false
		},
		/* 107 CommandResultAssignment <- <(ASSIGN Variable)> */
		nil,
		/* 108 Conditional <- <(IfStanza ElseIfStanza* ElseStanza?)> */
		nil,
		/* 109 IfStanza <- <(IF ConditionalExpression OPEN Block* CLOSE)> */
		func() bool {
			position391, tokenIndex391 := position, tokenIndex
			{
				position392 := position
				{
					position393 := position
					if !_rules[rule_]() {
						goto l391
					}
					if buffer[position] != rune('i') {
						goto l391
					}
					position++
					if buffer[position] != rune('f') {
						goto l391
					}
					position++
					if !_rules[rule_]() {
						goto l391
					}
					add(ruleIF, position393)
				}
				if !_rules[ruleConditionalExpression]() {
					goto l391
				}
				if !_rules[ruleOPEN]() {
					goto l391
				}
			l394:
				{
					position395, tokenIndex395 := position, tokenIndex
					if !_rules[ruleBlock]() {
						goto l395
					}
					goto l394
				l395:
					position, tokenIndex = position395, tokenIndex395
				}
				if !_rules[ruleCLOSE]() {
					goto l391
				}
				add(ruleIfStanza, position392)
			}
			return true
		l391:
			position, tokenIndex = position391, tokenIndex391
			return false
		},
		/* 110 ElseIfStanza <- <(ELSE IfStanza)> */
		nil,
		/* 111 ElseStanza <- <(ELSE OPEN Block* CLOSE)> */
		nil,
		/* 112 Loop <- <(LOOP ((OPEN Block* CLOSE) / (LoopConditionFixedLength OPEN Block* CLOSE) / (LoopConditionIterable OPEN Block* CLOSE) / (LoopConditionBounded OPEN Block* CLOSE) / (LoopConditionTruthy OPEN Block* CLOSE)))> */
		nil,
		/* 113 LoopConditionFixedLength <- <(COUNT (Integer / Variable))> */
		nil,
		/* 114 LoopConditionIterable <- <(LoopIterableLHS IN LoopIterableRHS)> */
		nil,
		/* 115 LoopIterableLHS <- <VariableSequence> */
		nil,
		/* 116 LoopIterableRHS <- <(Command / Variable)> */
		nil,
		/* 117 LoopConditionBounded <- <(Command SEMI ConditionalExpression SEMI Command)> */
		nil,
		/* 118 LoopConditionTruthy <- <ConditionalExpression> */
		nil,
		/* 119 ConditionalExpression <- <(NOT? (ConditionWithAssignment / ConditionWithCommand / ConditionWithRegex / ConditionWithComparator))> */
		func() bool {
			position405, tokenIndex405 := position, tokenIndex
			{
				position406 := position
				{
					position407, tokenIndex407 := position, tokenIndex
					{
						position409 := position
						if !_rules[rule_]() {
							goto l407
						}
						if buffer[position] != rune('n') {
							goto l407
						}
						position++
						if buffer[position] != rune('o') {
							goto l407
						}
						position++
						if buffer[position] != rune('t') {
							goto l407
						}
						position++
						if !_rules[rule__]() {
							goto l407
						}
						add(ruleNOT, position409)
					}
					goto l408
				l407:
					position, tokenIndex = position407, tokenIndex407
				}
			l408:
				{
					position410, tokenIndex410 := position, tokenIndex
					{
						position412 := position
						if !_rules[ruleAssignment]() {
							goto l411
						}
						if !_rules[ruleSEMI]() {
							goto l411
						}
						if !_rules[ruleConditionalExpression]() {
							goto l411
						}
						add(ruleConditionWithAssignment, position412)
					}
					goto l410
				l411:
					position, tokenIndex = position410, tokenIndex410
					{
						position414 := position
						if !_rules[ruleCommand]() {
							goto l413
						}
						{
							position415, tokenIndex415 := position, tokenIndex
							if !_rules[ruleSEMI]() {
								goto l415
							}
							if !_rules[ruleConditionalExpression]() {
								goto l415
							}
							goto l416
						l415:
							position, tokenIndex = position415, tokenIndex415
						}
					l416:
						add(ruleConditionWithCommand, position414)
					}
					goto l410
				l413:
					position, tokenIndex = position410, tokenIndex410
					{
						position418 := position
						if !_rules[ruleExpression]() {
							goto l417
						}
						{
							position419 := position
							{
								position420, tokenIndex420 := position, tokenIndex
								{
									position422 := position
									if !_rules[rule_]() {
										goto l421
									}
									if buffer[position] != rune('=') {
										goto l421
									}
									position++
									if buffer[position] != rune('~') {
										goto l421
									}
									position++
									if !_rules[rule_]() {
										goto l421
									}
									add(ruleMatch, position422)
								}
								goto l420
							l421:
								position, tokenIndex = position420, tokenIndex420
								{
									position423 := position
									if !_rules[rule_]() {
										goto l417
									}
									if buffer[position] != rune('!') {
										goto l417
									}
									position++
									if buffer[position] != rune('~') {
										goto l417
									}
									position++
									if !_rules[rule_]() {
										goto l417
									}
									add(ruleUnmatch, position423)
								}
							}
						l420:
							add(ruleMatchOperator, position419)
						}
						if !_rules[ruleRegularExpression]() {
							goto l417
						}
						add(ruleConditionWithRegex, position418)
					}
					goto l410
				l417:
					position, tokenIndex = position410, tokenIndex410
					{
						position424 := position
						{
							position425 := position
							{
								position426, tokenIndex426 := position, tokenIndex
								{
									position428 := position
									{
										position429 := position
										if !_rules[rule_]() {
											goto l427
										}
										if buffer[position] != rune('[') {
											goto l427
										}
										position++
										if !_rules[rule_]() {
											goto l427
										}
										add(ruleSQOPEN, position429)
									}
									if !_rules[ruleCommand]() {
										goto l427
									}
									{
										position430 := position
										if !_rules[rule_]() {
											goto l427
										}
										if buffer[position] != rune(']') {
											goto l427
										}
										position++
										if !_rules[rule_]() {
											goto l427
										}
										add(ruleSQCLOSE, position430)
									}
									add(ruleInlineCommand, position428)
								}
								goto l426
							l427:
								position, tokenIndex = position426, tokenIndex426
								if !_rules[ruleExpression]() {
									goto l405
								}
							}
						l426:
							add(ruleConditionWithComparatorLHS, position425)
						}
						{
							position431, tokenIndex431 := position, tokenIndex
							{
								position433 := position
								{
									position434 := position
									if !_rules[rule_]() {
										goto l431
									}
									{
										position435, tokenIndex435 := position, tokenIndex
										{
											position437 := position
											if !_rules[rule_]() {
												goto l436
											}
											if buffer[position] != rune('=') {
												goto l436
											}
											position++
											if buffer[position] != rune('=') {
												goto l436
											}
											position++
											if !_rules[rule_]() {
												goto l436
											}
											add(ruleEquality, position437)
										}
										goto l435
									l436:
										position, tokenIndex = position435, tokenIndex435
										{
											position439 := position
											if !_rules[rule_]() {
												goto l438
											}
											if buffer[position] != rune('!') {
												goto l438
											}
											position++
											if buffer[position] != rune('=') {
												goto l438
											}
											position++
											if !_rules[rule_]() {
												goto l438
											}
											add(ruleNonEquality, position439)
										}
										goto l435
									l438:
										position, tokenIndex = position435, tokenIndex435
										{
											position441 := position
											if !_rules[rule_]() {
												goto l440
											}
											if buffer[position] != rune('>') {
												goto l440
											}
											position++
											if buffer[position] != rune('=') {
												goto l440
											}
											position++
											if !_rules[rule_]() {
												goto l440
											}
											add(ruleGreaterEqual, position441)
										}
										goto l435
									l440:
										position, tokenIndex = position435, tokenIndex435
										{
											position443 := position
											if !_rules[rule_]() {
												goto l442
											}
											if buffer[position] != rune('<') {
												goto l442
											}
											position++
											if buffer[position] != rune('=') {
												goto l442
											}
											position++
											if !_rules[rule_]() {
												goto l442
											}
											add(ruleLessEqual, position443)
										}
										goto l435
									l442:
										position, tokenIndex = position435, tokenIndex435
										{
											position445 := position
											if !_rules[rule_]() {
												goto l444
											}
											if buffer[position] != rune('>') {
												goto l444
											}
											position++
											if !_rules[rule_]() {
												goto l444
											}
											add(ruleGreaterThan, position445)
										}
										goto l435
									l444:
										position, tokenIndex = position435, tokenIndex435
										{
											position447 := position
											if !_rules[rule_]() {
												goto l446
											}
											if buffer[position] != rune('<') {
												goto l446
											}
											position++
											if !_rules[rule_]() {
												goto l446
											}
											add(ruleLessThan, position447)
										}
										goto l435
									l446:
										position, tokenIndex = position435, tokenIndex435
										{
											position449 := position
											if !_rules[rule_]() {
												goto l448
											}
											if buffer[position] != rune('i') {
												goto l448
											}
											position++
											if buffer[position] != rune('n') {
												goto l448
											}
											position++
											if !_rules[rule_]() {
												goto l448
											}
											add(ruleMembership, position449)
										}
										goto l435
									l448:
										position, tokenIndex = position435, tokenIndex435
										{
											position450 := position
											if !_rules[rule_]() {
												goto l431
											}
											if buffer[position] != rune('n') {
												goto l431
											}
											position++
											if buffer[position] != rune('o') {
												goto l431
											}
											position++
											if buffer[position] != rune('t') {
												goto l431
											}
											position++
											if !_rules[rule__]() {
												goto l431
											}
											if buffer[position] != rune('i') {
												goto l431
											}
											position++
											if buffer[position] != rune('n') {
												goto l431
											}
											position++
											if !_rules[rule_]() {
												goto l431
											}
											add(ruleNonMembership, position450)
										}
									}
								l435:
									if !_rules[rule_]() {
										goto l431
									}
									add(ruleComparisonOperator, position434)
								}
								if !_rules[ruleExpression]() {
									goto l431
								}
								add(ruleConditionWithComparatorRHS, position433)
							}
							goto l432
						l431:
							position, tokenIndex = position431, tokenIndex431
						}
					l432:
						add(ruleConditionWithComparator, position424)
					}
				}
			l410:
				add(ruleConditionalExpression, position406)
			}
			return true
		l405:
			position, tokenIndex = position405, tokenIndex405
			return false
		},
		/* 120 ConditionWithAssignment <- <(Assignment SEMI ConditionalExpression)> */
		nil,
		/* 121 ConditionWithCommand <- <(Command (SEMI ConditionalExpression)?)> */
		nil,
		/* 122 ConditionWithRegex <- <(Expression MatchOperator RegularExpression)> */
		nil,
		/* 123 ConditionWithComparator <- <(ConditionWithComparatorLHS ConditionWithComparatorRHS?)> */
		nil,
		/* 124 ConditionWithComparatorLHS <- <(InlineCommand / Expression)> */
		nil,
		/* 125 ConditionWithComparatorRHS <- <(ComparisonOperator Expression)> */
		nil,
	}
	p.rules = _rules
	return nil
}
